workflows:
  ios-unsigned:
    name: iOS Unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean build
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace build
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign \
          --obfuscate --split-debug-info=build/ios/obfuscation

    artifacts:
      - build/ios/ipa/*.ipa
