name: film_shelf
description: "Movie Watchlist - Track your favorite films!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Keep this in dev_dependencies

# Add this new flutter_icons section right before the flutter section
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/FilmShelf.png"
  adaptive_icon_background: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/FilmShelf.png  # This should match the image_path above