# ios/Podfile - recommended for Flutter projects
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', 'Debug' => :debug, 'Release' => :release

generated_xcode_build_settings_path = File.join(__dir__, 'Flutter', 'Generated.xcconfig')
unless File.exist?(generated_xcode_build_settings_path)
  raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure Flutter tools have been run to generate it."
end

require File.join(__dir__, 'Flutter', 'podhelper.rb')

target 'Runner' do
  # If you do not need frameworks, you can remove `use_frameworks!`.
  # use_frameworks!
  use_frameworks! :linkage => :static 
  use_modular_headers!

  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
