platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

generated_xcode_build_settings_path = File.join(__dir__, 'Flutter', 'Generated.xcconfig')
unless File.exist?(generated_xcode_build_settings_path)
  raise "#{generated_xcode_build_settings_path} must exist. Run `flutter pub get` first."
end

require File.join(__dir__, 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
