# Minimal ios/Flutter/podhelper.rb (placeholder created for CI)
# The real podhelper is normally generated by Flutter tooling on macOS.
# This file defines the two functions the Podfile expects, as no-ops.

def install_all_flutter_pods(flutter_application_path)
  # no-op placeholder — Flutter on macOS will regenerate real pods if needed
end

def flutter_additional_ios_build_settings(target)
  # no-op placeholder
end
